ALTER TABLE "Profile" ADD COLUMN "workHours" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Profile" ADD COLUMN "freeHours" INTEGER NOT NULL DEFAULT 2;
ALTER TABLE "Profile" ADD COLUMN "sleepHours" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "Profile" ADD COLUMN "sleepAlarm" TEXT;
ALTER TABLE "Profile" ADD COLUMN "wakeAlarm" TEXT;
ALTER TABLE "Profile" ADD COLUMN "alarmsEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Profile" ADD COLUMN "trainingIntensityPreference" TEXT NOT NULL DEFAULT 'manter';
